trigger:
- master

pool:
 vmImage: 'windows-2019'

variables:
 BuildConfiguration: 'Release'

stages:
- stage: 'Build'
  jobs: 
  - job: 


    steps:
       - task: DotNetCoreCLI@2
         displayName: 'Build'
         inputs:
          command: build
          configuration: '--configuration $(BuildConfiguration)'


       - task: DotNetCoreCLI@2
         displayName: 'Restore'
         inputs:
          command: Restore      


       - task: DotNetCoreCLI@2
         displayName: 'Publish'
         inputs:
          command: publish
          arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
          publishWebProjects: false
          zipAfterPublish: false
          modifyOutputPath: false 

- stage: 'Test'
  jobs:
  - job: 
    steps:
        - task: DotNetCoreCLI@2
          displayName: 'Selenium run'
          inputs:
           command: custom
           projects: '**/SeleniumDemo.dll'
           custom: vstest
           arguments: '--logger:trx;logfilename=TEST.xml'
    
        - task: PublishTestResults@2
          displayName: 'Publish run results'
          inputs:
           testResultsFormat: VSTest
           testResultsFiles: '**/TEST.xml'
           mergeTestResults: true

     