
resources:
  containers:
  - container: 'DotNetImage'
    image: 'mcr.microsoft.com/dotnet/core/sdk:3.1'

trigger:
- master

pool:
 vmImage: 'windows-2019'

variables:
 BuildConfiguration: 'Release'
 

stages:
- stage: 'Build'
  jobs: 
  - job: 


    steps:
       - task: DotNetCoreCLI@2
         displayName: 'Build'
         inputs:
          command: build
          configuration: '--configuration $(BuildConfiguration)'


       - task: DotNetCoreCLI@2
         displayName: 'Restore'
         inputs:
          command: restore      


       - task: DotNetCoreCLI@2
         displayName: 'Publish'
         inputs:
          command: publish
          publishWebProjects: false
          arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
          zipAfterPublish: false
          modifyOutputPath: false 
       - task: PublishBuildArtifacts@1
         displayName: 'Publish Artifact'
         inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
          ArtifactName: 'drop'
          publishLocation: Container
         condition: succeededOrFailed()


          

- stage: 'Test'
  jobs:
  - job: 
    steps:
        
           
        - task: DotNetCoreCLI@2
          displayName: 'Selenium run'
          inputs:
           command: custom           
           projects: '**/SeleniumDemoYAML.dll'
           custom: vstest
           arguments: '--logger:trx;logfilename=TEST.xml'
    
        - task: PublishTestResults@2
          displayName: 'Publish run results'
          inputs:
           testResultsFormat: VSTest
           testResultsFiles: '**/TEST.xml'
           mergeTestResults: true
       
     